notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5a787de3f8e75d611ad2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

language: node_js
node_js:
  - v5
  - v4
  - '0.12'
  - '0.10'

after_script:
  - npm run coveralls
